name: Tests

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        php: [8.4]
        test-suite: ['Kronika', 'Kronika\Extension']
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer@v2

      - name: Validate Composer
        run: composer validate --strict

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: "php-${{ matrix.php }}-${{ matrix.os }}-${{ hashFiles('composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-${{ matrix.os }}-${{ hashFiles('composer.json') }}"

      - name: Install Composer
        run: composer install --dev --prefer-dist --no-progress

      - name: Run ${{ matrix.test-suit }} Tests
        uses: php-actions/phpunit@v4
        with:
          php_version: ${{ matrix.php }}
          configuration: phpunit.xml.dist
          testsuite: ${{ matrix.test-suite }}
